FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/client/package.json ./apps/client/
COPY libs/shared/package.json ./libs/shared/
RUN npm ci --ignore-scripts

COPY . .

RUN npx nx build client

FROM nginx:alpine
COPY --from=0 /app/apps/client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173
